/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.acktie.mobile.android.qr;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;


@Kroll.module(name = "Acktiemobileandroidqr", id = "com.acktie.mobile.android.qr")
public class AcktiemobileandroidqrModule extends KrollModule {
	
	private static final String moduleId = "com.acktie.mobile.android.qr";
	
	static {
		System.loadLibrary("iconv");
	}

	// Standard Debugging variables
	private static final String LCAT = "AcktiemobileandroidqrModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public AcktiemobileandroidqrModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is
		// created
	}

	public static String getModuleid() {
		return moduleId;
	}
}
